database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: postgres

  # the password
  password: secret

  # the JDBC URL
  url: jdbc:postgresql://0.0.0.0:5432/postgres
